"""Canary / onboarding selection and the task manifest.

    python -m datasea.manifest select      # print the deterministic canary + onboarding picks
    python -m datasea.manifest import      # import the picks into the catalog (refuses known-broken tasks)
    python -m datasea.manifest write       # write tasks/manifest.{md,jsonl} for the current catalog

Difficulty is a heuristic estimate from datasea/tasks/audit_facts.jsonl (run datasea.audit first):
    score = mutating_tools + verifiers / 2 + prompt_chars / 300
    easy <= 5.5 < medium <= 9 < hard
"Mutating tools" are selected tools whose names don't start with a read-only verb (list/get/search/...).
"""

import argparse
import json
import os
from typing import Any, Dict, List

from . import DATASEA_DIR
from .tasks import CATALOG_PATH, import_tasks, load_catalog, load_known_broken, save_catalog

FACTS_PATH = os.path.join(DATASEA_DIR, "tasks", "audit_facts.jsonl")
MANIFEST_MD = os.path.join(DATASEA_DIR, "tasks", "manifest.md")
MANIFEST_JSONL = os.path.join(DATASEA_DIR, "tasks", "manifest.jsonl")

PILOT_DOMAINS = ("email", "calendar", "drive", "teams")
CANARY_PLAN = (("easy", 2), ("medium", 2), ("hard", 1))  # per domain -> 20 tasks
ONBOARDING_PER_DOMAIN = 1
FIRST_TIME_MAX_PROMPT = 700


def load_facts() -> Dict[str, Dict[str, Any]]:
    with open(FACTS_PATH) as f:
        return {r["task_id"]: r for r in map(json.loads, f) if r}


def estimate(f: Dict[str, Any]) -> Dict[str, Any]:
    mutating = f["num_selected_tools"] - f["num_lookup_tools"]
    score = round(mutating + f["num_verifiers"] / 2 + f["prompt_chars"] / 300, 2)
    tier = "easy" if score <= 5.5 else "medium" if score <= 9 else "hard"
    first_time = tier == "easy" or (tier == "medium" and f["prompt_chars"] <= FIRST_TIME_MAX_PROMPT)
    return {"mutating_tools": mutating, "difficulty_score": score, "difficulty": tier,
            "first_time_suitable": first_time}


def _eligible(facts, broken, domain):
    return sorted(
        (f for f in facts.values()
         if f["domain"] == domain and f.get("live_audited") and not f["defects"] and f["task_id"] not in broken),
        key=lambda f: (estimate(f)["difficulty_score"], f["task_id"]),
    )


def _spread(items: List[Any], n: int) -> List[Any]:
    """n items evenly spaced through a sorted list (avoids always taking the extremes)."""
    if n >= len(items):
        return list(items)
    return [items[int((i + 0.5) * len(items) / n)] for i in range(n)]


def select() -> Dict[str, List[str]]:
    facts, broken = load_facts(), load_known_broken()
    picks = {"canary": [], "onboarding": []}
    for d in PILOT_DOMAINS:
        pool = _eligible(facts, broken, d)
        by_tier = {t: [f for f in pool if estimate(f)["difficulty"] == t] for t, _ in CANARY_PLAN}
        chosen = []
        for tier, n in CANARY_PLAN:
            got = _spread(by_tier[tier], n)
            if len(got) < n:
                raise SystemExit(f"{d}: only {len(got)} eligible {tier} tasks")
            chosen += [f["task_id"] for f in got]
        picks["canary"] += chosen
        easy_left = [f for f in by_tier["easy"] if f["task_id"] not in chosen]
        picks["onboarding"] += [f["task_id"] for f in easy_left[:ONBOARDING_PER_DOMAIN]]
    return picks


def build_manifest() -> List[Dict[str, Any]]:
    facts, broken = load_facts(), load_known_broken()
    rows = []
    for tid, e in load_catalog().items():
        f = facts[tid]
        rows.append({
            "task_id": tid, "domain": e["domain"], "pool": e.get("pool"), "pilot_only": e["pilot_only"],
            **estimate(f),
            "num_tools": f["num_selected_tools"], "cross_app": f["cross_app"], "gyms": f["gyms"],
            "num_verifiers": f["num_verifiers"], "verifier_types": f["verifier_types"],
            "prompt_chars": f["prompt_chars"], "known_broken": tid in broken,
            "hf_revision": e["source"]["hf_revision"],
        })
    order = {d: i for i, d in enumerate(PILOT_DOMAINS)}
    rows.sort(key=lambda r: (r["pool"] != "onboarding", order.get(r["domain"], 9), r["difficulty_score"]))
    return rows


def write_manifest() -> None:
    rows = build_manifest()
    with open(MANIFEST_JSONL, "w") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    rev = rows[0]["hf_revision"] if rows else "?"
    lines = [
        "# DataSea pilot task manifest",
        "",
        f"Source: ServiceNow-AI/EnterpriseOps-Gym, oracle split, revision `{rev}`, unmodified.",
        "All tasks are pilot_only (public benchmark tasks; never use as untouched eval data).",
        "Known-broken tasks (datasea/tasks/known_broken.jsonl) are excluded. Generated by `python -m datasea.manifest write`.",
        "",
        "Difficulty is a heuristic: mutating tools + verifiers/2 + prompt chars/300 (easy <= 5.5 < medium <= 9 < hard).",
        "",
        "| pool | domain | task_id | difficulty (score) | tools (mutating) | cross-app | verifiers | first-time worker |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['pool']} | {r['domain']} | `{r['task_id']}` | {r['difficulty']} ({r['difficulty_score']}) | "
            f"{r['num_tools']} ({r['mutating_tools']}) | {'yes' if r['cross_app'] else 'no'} | {r['num_verifiers']} | "
            f"{'yes' if r['first_time_suitable'] else 'no'} |")
    with open(MANIFEST_MD, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {len(rows)} rows to {MANIFEST_MD} and {MANIFEST_JSONL}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("cmd", choices=("select", "import", "write"))
    p.add_argument("--revision", default="main")
    args = p.parse_args()
    if args.cmd == "write":
        return write_manifest()
    picks = select()
    if args.cmd == "select":
        print(json.dumps(picks, indent=2))
        return
    facts = load_facts()
    catalog = {}
    for pool, ids in picks.items():
        for d in PILOT_DOMAINS:
            dom_ids = [t for t in ids if facts[t]["domain"] == d]
            for e in import_tasks(d, dom_ids, pool, revision=args.revision):
                catalog[e["task_id"]] = e
    save_catalog(catalog)
    print(f"catalog rebuilt with {len(catalog)} tasks -> {CATALOG_PATH}")
    write_manifest()


if __name__ == "__main__":
    main()
